name: Build and deploy Cinesplain to Production

on:
  push:
    branches:
      - main

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.402'

      - name: Get node_modules cache
        uses: actions/cache@v4
        id: node_modules_cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Get nuget cache
        uses: actions/cache@v4
        id: nuget_cache
        with:
          path: |
            **/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/Cinesplain.Server.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - if: ${{ steps.node_modules_cache.outputs.cache-hit != 'true' }}
        name: Create .npmrc file
        run: |
          echo "@${{vars.USERNAME}}:registry=https://npm.pkg.github.com/" > cinesplain.client/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.AUTH_TOKEN }}" >> cinesplain.client/.npmrc

      - if: ${{ steps.nuget_cache.outputs.cache-hit != 'true' }}
        name: Authenticate private nuget repo
        run:
          dotnet nuget add source --username ${{vars.USERNAME}} --password ${{ secrets.AUTH_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{vars.USERNAME}}/index.json"

      - name: Build with dotnet
        run: dotnet build -c Release

      - name: dotnet publish
        run: dotnet publish -c Release -property:PublishDir="${{env.DOTNET_ROOT}}/cinesplain"
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{env.DOTNET_ROOT}}/cinesplain"

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9CA1B234455C4A2598C8270BCBC67114 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8682499B5FB1430BBCCEEB99F19FF03D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EEEAF4BDD3A047D4BFAFF5D710280855 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cinesplain'
          slot-name: 'Production'
          package: .
          
