name: Build and deploy ASP.Net Core app to Azure Web App - cinesplain

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{ github.workspace }}/Output

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-app-artifacts
          path: ${{ github.workspace }}/Output

  deploy:
    needs: build
    runs-on: windows-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    steps:
      - name: List Published Package
        run: ls -R ${{ github.workspace }}/Output

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: web-app-artifacts
          path: ${{ github.workspace }}/Output
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9CA1B234455C4A2598C8270BCBC67114 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8682499B5FB1430BBCCEEB99F19FF03D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EEEAF4BDD3A047D4BFAFF5D710280855 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cinesplain'
          package: ${{ github.workspace }}\Output
          slot-name: 'Production'
          
